// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func GetData(ctx context.Context, c *app.RequestContext) {
	ch := make(chan int)
	go assignValue(ch)
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
		"data":    <-ch,
	})
}

func assignValue(ch chan int) {
	ch <- 10
}
